### ISSUE TITLE
Error in Safari when re-rendering stage

### ISSUE THREAD

**Issue by JoostKiens** [michalochman/react-pixi-fiber#164] opened 2020-01-27 10:27 UTC
Hi! First of all, thanks for the amazing work on this library! 

However I'm trying to upgrade from 0.9.3 to 0.12.1 and I'm encountering a bug in Safari 13.0.4. on MacOS.

### Description
A fatal error error occurs in the latest version of react-pixi-fiber in Safari when re-rendering the `Stage`.

### Steps to reproduce
1. Go to [https://codesandbox.io/s/cranky-snowflake-8xrn0](https://codesandbox.io/s/cranky-snowflake-8xrn0) with Safari (I use 13.0.4)
2. Click anywhere on the window to update the state
3. Stage tries to re-render
4. The following error occurs: 
```
TypeError
null is not an object (evaluating 'attributes.stencil')
```

### Additional info
This error does not occur in Chrome & Firefox.

- react-pixi-fiber version: 0.12.1
- React version: 16.12.0
- ReactDOM version: 16.12.0
- PixiJS version: 5.2.0

Let me know if you need more info👍.

**Comment by michalochman** [comment] 2020-01-27 11:03
Hello @JoostKiens, there are no references to `attributes` or `attributes.stencil` in the library itself so it might be an issue with your code. However, there is a known issue when re-rendering hook-based `Stage` component (see #156) which might be what you experience.

You can solve that issue by either installing `react-pixi-fiber@1.0.0-beta.0` or importing class-based `Stage`:

```jsx
import { createStageClass } from "react-pixi-fiber"

const Stage = createStageClass()
```

and then using that created `Stage` instead of directly imported one.

Let me know if that solves the issue for you.

**Comment by michalochman** [comment] 2020-01-27 11:05
Actually, I have edited your code sandbox with the above code and it seems to fix it, so I'm closing this.

**Closed by michalochman** 2020-01-27 11:05 UTC

**Comment by JoostKiens** [comment] 2020-01-27 12:08
Yeah, `createStageClass` works fine. 👍

Thanks for your help!

**Comment by antoniobrandao** [comment] 2021-09-30 19:05
This was also happening for me.

Using createStageClass() and/or react-pixi-fiber@1.0.0-beta.X (up to beta13) didn't work for me, problem persisted.

I was using Safari 14.x. I noticed in the console that only WebGL1 was active, not WebGL2.

After activating WebGL2 in Safari (via Develop menu > Experimental features), the problem is gone.

So it was happening specifically when only WebGL1 is active and doesn't happen with WebGL 2. 

Today I reverted my Safari to all defaults, and installed Safari 15. Safari 15 has WebGL 2 already active by default, and so this problem is gone there.

Still, whoever visits my app using Safari 14.x or below, will get the error and I will have to have to use canvas fallback in those cases.

**Comment by michalochman** [comment] 2021-09-30 21:02
@antoniobrandao can you provide a sandbox (eg. using https://codesandbox.io/) proving this is an issue of react-pixi-fiber and not just PixiJS?

**Comment by antoniobrandao** [comment] 2021-10-01 13:45
@michalochman hey Michal, thanks for the reply. I unsuccessfully tried to create a codesandbox project, and gave up. So I created a stripped-down version of my project where you can see only the little bit that matters.

Repo is here: https://github.com/antoniobrandao/hb3

It's a Gatsby project. Just run `yarn` and then `yarn develop` and it should run fine. It may not be a sweet codesandbox, but it's a real-world project which is also useful.

Try it in Safari - make sure you're not using Safari 15, but an earlier version. I was using 14.x when the error was happening, in it's default state, where WebGL2 is not active by default so the pixi notification in the console says "WebGL1" and not "2".

The project will display a page with an animation and links to 3 pages. In a Safari <15, try navigating through the 3 pages. Also, try resizing your browser window.

If you're using Safari <15, without WebGL2 manually enabled in the "Experimental features", you should see that `stencil`-related error.

Hope this helps.

**Comment by michalochman** [comment] 2021-10-01 15:38
@antoniobrandao my main concern was whether it is a react-pixi-fiber issue or just PixiJS issue, i.e. try to do the same but 
 with bare PixiJS code, without using react-pixi-fiber at all.

For example, here https://github.com/antoniobrandao/hb3/blob/master/src/components/sections/home/pixireact/pixiBg.js#L30-L37 you could just return `<ParticlesCanvas ref={someRef} />` and then do what you want in PixiJS inside some `useEffect`, creating `PIXI.Application` inside that div.
