### ISSUE TITLE
Q: CustomPIXIComponent, re-render when refresh props

### ISSUE THREAD

**Issue by fbove** [michalochman/react-pixi-fiber#75] opened 2018-09-27 18:06 UTC
Hi!
I have an issue with a CustomPIXIComponent.
When my component state is refreshed, CustomPIXIComponent inside it, is not.

```javascript
import Graphics from './Graphics'
// .....
render() (
  // render method is getting called for re-rendering
  this.state.arrows.map(arrow => (
    <Graphics
      key={`${arrow.from.id}-${arrow.to.id}`}
      from={arrow.from}
      to={arrow.to}
    />
  ))
)
```

```javascript
import { CustomPIXIComponent } from 'react-pixi-fiber'
import * as PIXI from 'pixi.js'

const TYPE = 'Arrow'
export const behavior = {
  customDisplayObject: () => new PIXI.Graphics(),
  customApplyProps(instance, oldProps, newProps) {
    // but this is not called
    this.applyDisplayObjectProps(oldProps, newProps)
  }
}

export default CustomPIXIComponent(behavior, TYPE)
```

Probably I shouldn't expect CustomPIXIComponent to re-apply props.
Any advice on how to do this?

**Comment by michalochman** [comment] 2018-09-28 05:53
Hi @fbove, `customApplyProps` is not called unless the props change.

Could you explain what is your use case exactly so I can think understand it? In most scenarios it makes no sense to re-apply props (potentially costly operation) if they didn't change.

**Comment by fbove** [comment] 2018-09-28 14:16
The example is:

```javascript
import React from 'react'
import PropTypes from 'prop-types'

import Graphics from './Graphics'

class Arrows extends React.Component {
  findNode = nodeId => this.props.nodes.find(node => node.id === nodeId)
  computedArrows = () =>
    this.props.arrows.map(arrow => ({
      from: this.findNode(arrow.from),
      to: this.findNode(arrow.to)
    }))
  render() {
    // re-render here is ok (1)
    const arrows = this.computedArrows().map(arrow => (
      <Graphics
        key={`${arrow.from.id}-${arrow.to.id}`}
        from={arrow.from}
        to={arrow.to}
      />
    ))
    return arrows
  }
}

Arrows.propTypes = {
  nodes: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      x: PropTypes.number.isRequired,
      y: PropTypes.number.isRequired,
      w: PropTypes.number.isRequired,
      h: PropTypes.number.isRequired
    })
  ),
  arrows: PropTypes.arrayOf(
    PropTypes.shape({
      from: PropTypes.string.isRequired,
      to: PropTypes.string.isRequired
    })
  )
}

export default Arrows
```

```javascript
import { CustomPIXIComponent } from 'react-pixi-fiber'
import * as PIXI from 'pixi.js'

const TYPE = 'Arrow'
export const behavior = {
  customDisplayObject: () => new PIXI.Graphics(),
  customApplyProps(instance, oldProps, newProps) {
    // Here I read "from" and "to" from newProps and create lines.
    // but this is not called
    this.applyDisplayObjectProps(oldProps, newProps)
  }
}

export default CustomPIXIComponent(behavior, TYPE)
```

Arrows is receiving updated props and re-rendering (1), but CustomPIXIComponent it's not. And it does have new props to show.

A workaround was to reset arrows on the state, inside the Component where I'm using Arrows.
```javascript
this.setState({ arrows: [] })
this.setState({
  arrows: [...arrowsResp.arrows]
})
```

It'd probably be some React behavior I'm not aware of.

**Comment by michalochman** [comment] 2018-09-28 20:59
Do I understand correctly that you mean that the props are not applied the first time the `CustomPIXIComponent` object is created? If yes, then this is intended behaviour. You have `customDisplayObject` method for instantiation, where you can also apply any props you like.

`customDisplayObject: () => new PIXI.Graphics(),` is the easiest implementation, you could do something like this instead:

```
customDisplayObject: (props) => {
  const g = new PIXI.Graphics()
  // apply props to g here
  // ...
  return g
},
```

`customApplyProps` is then only called on subsequent renders. `applyDisplayObjectProps` is only a hook for your custom component that calls default, `react-pixi-fiber` function for applying props to components.

**Comment by michalochman** [comment] 2018-10-10 15:11
Closing as I think the above is the correct way to solve this. Let me know if not.

**Closed by michalochman** 2018-10-10 15:11 UTC
Labels: question
