### ISSUE TITLE
Bug in Hooks: ReactPixiFiber did not render into container provided 

### ISSUE THREAD

**Issue by Othreumaru** [michalochman/react-pixi-fiber#156] opened 2019-12-10 11:27 UTC
### Description

I believe around version 0.10.0 with PR 
https://github.com/michalochman/react-pixi-fiber/pull/127

A subtle bug was introduced. It can occur when react renders a component then that render triggers a change for example layout resize which triggers rerender in a sync way. Which causes fiber to unmount previous  component which throws exception 

ReactPixiFiber did not render into container provided 

This happens because in hooks.js inside usePixiAppCreator inside useLayoutEffect you return a function that expects that component was already mounted. However not is perfectly normal in react for that method to be called before component is mounted.

### Steps to reproduce

1. Render something that changes state and causes another render in same stack 
2.

### Additional info

- react-pixi-fiber version: 0.10.0
- React version: ^16.10.1
- ReactDOM version: ^16.10.1
- PixiJS version: ^5.1.5

**Comment by michalochman** [comment] 2019-12-10 12:29
@Othreumaru can you reproduce this also in 0.12.0? If you could provide some code sandbox with this happening that would be great. You can use [this template](https://codesandbox.io/s/react-pixi-fiber-template-ohk6z) as a starter.

**Comment by Othreumaru** [comment] 2019-12-10 14:40
I have narrowed down the root cause of my problem to be options object changing on Stage causing a circular unmount loop since that was triggering update to my context. My case might be rare so feel free to close this.

**Comment by michalochman** [comment] 2019-12-10 14:55
I can see if it is possible to eliminate such unmount loop if you could share a minimal options object that could be used to reproduce that scenario.

**Comment by nstolpe** [comment] 2019-12-22 04:07
I'm pretty sure I'm also running into this issue. I'll try to recreate it and fix it.

**Comment by michalochman** [comment] 2019-12-22 08:45
@nstolpe I have changed how it works significantly in #47 so not sure if it's worth fixing on master unless this is a common issue.

**Comment by nstolpe** [comment] 2019-12-22 09:24
Actually, I think my issue has something to do with my app code. [This example](https://codesandbox.io/s/laughing-sun-3fx7m) of changing `backgroundColor` in Stage options works fine. It's just `useState` though, no Context. I have tested locally with a Context and that's fine too, I'll try to est up an example for that as well. @michalochman if @Othreumaru can get us an example that reproduces the issue I'm happy to help look into resolving it.

**Comment by nstolpe** [comment] 2019-12-22 09:29
@michalochman oh wow, you've made some major changes. I didn't see your reply until after posting my last one. If there are any outstanding issues with this after your refactor, or if you just need some testing done, I can help out.

**Comment by vojto** [comment] 2020-01-16 14:39
Getting the same error. Not sure what's going on, because it's part of pretty complex app.

Any update on #47 getting merged in?

**Comment by nstolpe** [comment] 2020-01-16 15:22
@vojto I've encountered another issue that seems related to this one. To work around it until 47 is merged, you can try the workaround I've been using, which is to use the PXI Stage class instead. Import [createStageClass](https://github.com/michalochman/react-pixi-fiber/blob/master/src/Stage.js#L72) and call it to get your Stage component.

**Comment by vojto** [comment] 2020-01-16 15:30
@nstolpe Thanks for that. I just got #47 running locally, so I'm gonna play with that for a while, and if it fails, I'll try your approach.

FYI for anyone who wants to run this from another branch. I didn't have much luck adding it as Yarn dependency from Git, so what I ended up doing was just opening my `node_modules/` and replacing contents of `cjs` with a copy of built files from another branch.

**Comment by michalochman** [comment] 2020-01-16 19:25
@vojto I am pretty happy with #47, however I'm a little afraid that the way it works now may give a lot of users heart attacks due to the amount of warnings – I have decided to make these warnings opt-in instead, but extra work will be needed. I'm currently exploring [`React.StrictMode`](https://reactjs.org/docs/strict-mode.html) and if that ends well, I'll be pretty much ready to release 1.0.0

**Comment by michalochman** [comment] 2020-01-19 16:27
I have just released `react-pixi-fiber@1.0.0-beta.0` with (#47 merged) if anyone wants to give it a try.

**Comment by michalochman** [comment] 2020-01-23 20:57
@vojto @nstolpe were you able to fix your issues with that version? Can we close this issue?

I hope there were no braking changes introduced other than `_app` variable available on class-based `Stage` ref being converted to `React.createRef`.

**Comment by maerzhase** [comment] 2020-01-24 17:00
bug seems to be resolved with `react-pixi-fiber@1.0.0-beta.0`. I can't reproduce it anymore.

**Comment by vojto** [comment] 2020-01-25 05:06
Works very well for me.

**Comment by nstolpe** [comment] 2020-01-26 01:26
@michalochman sorry, just got some time to work on my project. Both issues I mentioned here seem to have been cleared up now.

**Comment by nstolpe** [comment] 2020-07-26 05:37
@michalochman I've been using [1.0.0-beta.1](https://www.npmjs.com/package/react-pixi-fiber/v/1.0.0-beta.1) for a while now, but see that master has been updated more recently. Is the beta still the best branch to stick with?

**Comment by michalochman** [comment] 2020-07-26 07:45
@nstolpe I will update the beta branch today if you're an active user.

There are several reasons it has staled:
- the production bundle size is about 10 kB larger than current version (before gzip) and I'm evaluating if it should be that way
- `react-dom` itself has shifted away from aggressive props validation which was the driver behind major update (and the base of it, so I'll have to review `react-dom` code again)
- there is an open question how to deal with props introduced by PixiJS plugins

**Comment by michalochman** [comment] 2020-07-26 19:09
Turns out it will take me more time to rebase beta to `master` (looks like I missed some functionality there, like providing `app` prop to `Stage`), but I've started it already so expect it soon.

**Comment by michalochman** [comment] 2020-07-27 10:16
@nstolpe I have just published [1.0.0-beta.2](https://www.npmjs.com/package/react-pixi-fiber/v/1.0.0-beta.2) with all features that were missing from the current branch.

**Comment by nstolpe** [comment] 2020-07-28 17:33
@michalochman thanks for the update and for doing that so fast. I'll update to the new beta tonight.

**Comment by linonetwo** [comment] 2020-08-31 14:22
I can confirm `"react-pixi-fiber": "^1.0.0-beta.4",` works very well!

Now hot module replacement won't break my game anymore.

**Comment by michalochman** [comment] 2022-07-19 15:38
`react-pixi-fiber@1.0.0` released.

**Closed by michalochman** 2022-07-19 15:38 UTC
Labels: bug, fixed in 1.0.0
