### ISSUE TITLE
Context and TypeScript (React 16.5.2)

### ISSUE THREAD

**Issue by casperstorm** [michalochman/react-pixi-fiber#81] opened 2018-11-01 14:42 UTC
### Description
How do you use `Context` in TypeScript? By reading [this paragraph](https://github.com/michalochman/react-pixi-fiber#context--accessing-pixiapplication-instance-created-by-stage-) it looks like I can use either `withApp` (HOC) or the `Context` API directly. Looking in the [`index.d.ts`](https://github.com/michalochman/react-pixi-fiber/blob/master/index.d.ts) file it does not expose anything so importing either fails:

```ts
import { AppContext, withApp } from "react-pixi-fiber"
```

### Additional info

- react-pixi-fiber version: `0.5.0`
- React version: `16.5.2`
- ReactDOM version: `16.5.2`
- PixiJS version: `4.8.2`

**Comment by michalochman** [comment] 2018-11-01 15:19
@casperstorm try to run it against the code in #76. I am no expert in TypeScript so I can't help much more for now. I was basically waiting for someone to confirm that it works as intended before merging.

**Comment by michalochman** [comment] 2018-11-02 09:41
@casperstorm released as react-pixi-fiber@0.5.1

**Closed** 2018-11-02 09:40 UTC
